on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  my-action:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: joabalea/App-Center-action@v1.0.2
        with:
          command: appcenter codepush release-react -a michelalmeidasilva/ReactNativeRedux
          token: ${{secrets.APP_CENTER_LOGIN}}
